"""empty message

Revision ID: 4358ce28ee26
Revises: e0b8ddfc669e
Create Date: 2025-09-26 09:45:12.547376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4358ce28ee26'
down_revision = 'e0b8ddfc669e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
